### ISSUE TITLE
Heroku maintenance mode off broken

### ISSUE THREAD

**Issue by jweakley** [wildland/wildland_dev_tools#47]
```
module.js:557
    throw err;
    ^

Error: Cannot find module '/Users/jweakley/.local/share/heroku/client/package.json'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at run (/Users/jweakley/.local/share/heroku/client/node_modules/@cli-engine/engine/lib/cli.js:82:22)
    at Object.<anonymous> (/Users/jweakley/.local/share/heroku/client/bin/heroku.js:7:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
Turning off maintenance mode for production
module.js:557
    throw err;
    ^

Error: Cannot find module '/Users/jweakley/.local/share/heroku/client/package.json'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at run (/Users/jweakley/.local/share/heroku/client/node_modules/@cli-engine/engine/lib/cli.js:82:22)
    at Object.<anonymous> (/Users/jweakley/.local/share/heroku/client/bin/heroku.js:7:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
```

**Comment by jweakley** [comment]
This is actually an issue with the heroku CLI. The readme should include which version is required and the script should inform you if you don't have the CLI installed.
